import type { ItemDef, ItemStack, Inventory } from "../core/types";

/**
 * The item catalogue.
 *
 * Sprites point at `world/items/<id>.png`, generated by the art pipeline.
 * Anything the renderer cannot find falls back to a drawn placeholder, so the
 * simulation is playable before the art batch lands.
 */

const ITEM_LIST: readonly ItemDef[] = [
  { id: "gold", name: "gold coin", kind: "gold", weight: 0.1, stackable: true, value: 1, sprite: "gold" },
  { id: "shard", name: "portal shard", kind: "material", weight: 0.5, stackable: true, value: 12, sprite: "shard" },

  { id: "tonic", name: "travel tonic", kind: "potion", weight: 2.5, stackable: true, value: 45, heal: 0.42, sprite: "tonic" },
  { id: "greater-tonic", name: "greater tonic", kind: "potion", weight: 3.5, stackable: true, value: 120, heal: 0.75, sprite: "greater-tonic" },

  { id: "worn-blade", name: "worn blade", kind: "weapon", weight: 38, stackable: false, value: 40, sprite: "worn-blade" },
  { id: "caravan-sabre", name: "caravan sabre", kind: "weapon", weight: 42, stackable: false, value: 220, sprite: "caravan-sabre" },
  { id: "warden-glaive", name: "warden glaive", kind: "weapon", weight: 58, stackable: false, value: 900, sprite: "warden-glaive" },

  { id: "travel-cloak", name: "travel cloak", kind: "armor", weight: 30, stackable: false, value: 55, sprite: "travel-cloak" },
  { id: "porter-mail", name: "porter mail", kind: "armor", weight: 62, stackable: false, value: 300, sprite: "porter-mail" },
  { id: "warden-plate", name: "warden plate", kind: "armor", weight: 88, stackable: false, value: 1100, sprite: "warden-plate" },

  { id: "ember-charm", name: "ember charm", kind: "armor", weight: 3, stackable: false, value: 180, sprite: "ember-charm" },

  { id: "evolution-crystal", name: "evolution crystal", kind: "material", weight: 6, stackable: true, value: 260, sprite: "evolution-crystal" },
  { id: "warden-relic", name: "warden relic", kind: "trophy", weight: 12, stackable: true, value: 750, sprite: "warden-relic" },

  { id: "ash-carapace", name: "ash carapace", kind: "trophy", weight: 8, stackable: true, value: 22, sprite: "ash-carapace" },
  { id: "creek-pearl", name: "creek pearl", kind: "trophy", weight: 2, stackable: true, value: 38, sprite: "creek-pearl" },
  { id: "root-heart", name: "root heart", kind: "trophy", weight: 9, stackable: true, value: 55, sprite: "root-heart" },
  { id: "geode-core", name: "geode core", kind: "trophy", weight: 15, stackable: true, value: 90, sprite: "geode-core" },
  { id: "veil-dust", name: "veil dust", kind: "trophy", weight: 1, stackable: true, value: 140, sprite: "veil-dust" },
  { id: "aurora-quill", name: "aurora quill", kind: "trophy", weight: 2, stackable: true, value: 210, sprite: "aurora-quill" },
] as const;

const BY_ID = new Map(ITEM_LIST.map((item) => [item.id, item]));

export const ITEMS: readonly ItemDef[] = ITEM_LIST;

export function itemDef(defId: string): ItemDef {
  const found = BY_ID.get(defId);
  if (!found) throw new Error(`Unknown item: ${defId}`);
  return found;
}

export function itemSpritePath(defId: string): string {
  return `/game-assets/world/items/${itemDef(defId).sprite}.png`;
}

/** Frame key for this item inside the packed `items` atlas. */
export function itemAtlasFrame(defId: string): string {
  return itemDef(defId).sprite;
}

/** Total weight carried. */
export function inventoryWeight(inventory: Inventory): number {
  const carried = inventory.stacks.reduce((sum, stack) => sum + itemDef(stack.defId).weight * stack.count, 0);
  return Math.round((carried + inventory.gold * 0.1) * 10) / 10;
}

/** Capacity grows with level, so a stronger Porter hauls more loot home. */
export function capacity(level: number): number {
  return 400 + level * 20;
}

/**
 * Merge a stack into a list, respecting stackability. Returns a new array so
 * callers stay free of mutation.
 */
export function addToStacks(stacks: readonly ItemStack[], incoming: ItemStack): ItemStack[] {
  const def = itemDef(incoming.defId);
  if (!def.stackable) return [...stacks, incoming];
  const index = stacks.findIndex((stack) => stack.defId === incoming.defId);
  if (index < 0) return [...stacks, incoming];
  const next = [...stacks];
  next[index] = { ...next[index], count: next[index].count + incoming.count };
  return next;
}

export function removeFromStacks(stacks: readonly ItemStack[], instanceId: string, count?: number): ItemStack[] {
  const index = stacks.findIndex((stack) => stack.instanceId === instanceId);
  if (index < 0) return [...stacks];
  const stack = stacks[index];
  const taken = count ?? stack.count;
  const next = [...stacks];
  if (taken >= stack.count) next.splice(index, 1);
  else next[index] = { ...stack, count: stack.count - taken };
  return next;
}

export function findStack(stacks: readonly ItemStack[], defId: string): ItemStack | undefined {
  return stacks.find((stack) => stack.defId === defId);
}

/** Everything drinkable the Porter is carrying, for the potion chooser. */
export function carriedPotions(inventory: Inventory): ItemStack[] {
  return inventory.stacks.filter((stack) => (itemDef(stack.defId).heal ?? 0) > 0);
}
